INSERT INTO Articles
    (author, title, journal, year, volume, number, pages)
    VALUES
    ('Alex Williams', 'Pioneering Sustainable IT with Green Computing', 'Communications of the ACM', 2024, NULL, NULL, NULL),
    ('Devin N. Perkins and Marie-Noel {Brune Drisse} and Tapiwa Nxele and Peter D. Sly', 'E-Waste: A Global Hazard', 'Annals of Global Health', 2014, '80', '4', '286-295')
    ON CONFLICT DO NOTHING;

INSERT INTO Books
    (author, year, title, publisher, address)
    VALUES
    ('Terhi Aaltonen-Ogbeide, Kai K. Kimppa, Irmeli Lamberg, Pentti Saastamoinen, Olli I. Heimo', 2014, 'Silmät auki IT-etiikkaan', 'Eduskunta', '')
    ON CONFLICT DO NOTHING;

INSERT INTO Inproceedings
    (author, title, booktitle, year, pages, address, publisher)
    VALUES
    ('Xiang, Biao and Jiang, Daxin and Pei, Jian and Sun, Xiaohui and Chen, Enhong and Li, Hang', 'Context-Aware Ranking in Web Search', 'Proceedings of the 33rd International ACM SIGIR Conference on Research and Development in Information Retrieval (SIGIR ''10'')', 2010, '451-458', 'New York, NY, USA', 'Association for Computing Machinery')
    ON CONFLICT DO NOTHING;

-- This one is generated by ChatGPT, so it is not real
INSERT INTO Manuals
    (title, year, author, organization, address)
    VALUES
    ('Introduction to Computational Algorithms and Data Structures', 2023, 'Jane Doe and John Smith', 'Institute of Advanced Computing', 'Cambridge, MA, USA')
    ON CONFLICT DO NOTHING;
